server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true

scalar:
  enabled: true
  path: /scalar
  sources:
    - url: /v3/api-docs/public-api
      title: Public API
      slug: public
      isDefault: true
    - url: /v3/api-docs/admin-api
      title: Admin API
      slug: admin
